// Instruction
export const SHOW_INSTRUCTION = 'SHOW_INSTRUCTION'
export const CLOSE_INSTRUCTION = 'CLOSE_INSTRUCTION'
export const CHANGE_BRIEF = 'CHANGE_BRIEF'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const SET_DESTID = 'SET_DESTID'
export const SET_INTRO = 'SET_INTRO'
export const SHOW_ITS_BUSINESS = 'SHOW_ITS_BUSINESS'
export const SHOW_ITS_INDOOR = 'SHOW_ITS_INDOOR'

//Map
export const CHANGE_FLOOR = 'CHANGE_FLOOR'
export const SET_MAPLAYER = 'SET_MAPLAYER'
export const SET_VECTORLAYER = 'SET_VECTORLAYER'
export const SET_F1LAYER = 'SET_F1LAYER'
export const SET_F2LAYER = 'SET_F2LAYER'
export const SET_F3LAYER = 'SET_F3LAYER'
export const SET_F4LAYER = 'SET_F4LAYER'
export const SET_LAYERS = 'SET_LAYERS'

// Navigate
export const SHOW_NAVIGATE = 'SHOW_NAVIGATE'
export const CLOSE_NAVIGATE = 'CLOSE_NAVIGATE'
export const SHOW_CHOOSESTART = 'SHOW_CHOOSESTART'
export const CLOSE_CHOOSESTART = 'CLOSE_CHOOSESTART'
export const SHOW_CHOOSEDIRECTION = 'SHOW_CHOOSEDIRECTION'
export const CLOSE_CHOOSEDIRECTION = 'CLOSE_CHOOSEDIRECTION'
export const SHOW_ALLSTARTS = 'SHOW_ALLSTARTS'
export const SHOW_PARTIALSTARTS = 'SHOW_PARTIALSTARTS'
export const SHOW_ALLDIRECTIONS = 'SHOW_ALLDIRECTIONS'
export const SHOW_PARTIALDIRECTIONS = 'SHOW_PARTIALDIRECTIONS'
export const SHOW_BUTTON = 'SHOW_BUTTON'
export const DISABLE_BUTTON = 'DISABLE_BUTTON'
export const SET_START = 'SET_START'
export const SET_DEST = 'SET_DEST'
export const SET_CHECKSTART = 'SET_CHECKSTART'
export const SET_CHECKDEST = 'SET_CHECKDEST'
export const SET_VUEMAP = 'SET_VUEMAP'
export const SET_ROUTE = 'SET_ROUTE'
export const SHOW_NAVIGATE_CONTENT = 'SHOW_NAVIGATE_CONTENT'
export const CLOSE_NAVIGATE_CONTENT = 'CLOSE_NAVIGATE_CONTENT'

// Coordinate
export const SET_STARTCOORDINATE = 'SET_STARTCOORDINATE'
export const SET_DIRECTIONCOORDINATE = 'SET_DIRECTIONCOORDINATE'

// SearchFloat
export const SHOW_SEARCHFLOAT = 'SHOW_SEARCHFLOAT'
export const CLOSE_SEARCHFLOAT = 'CLOSE_SEARCHFLOAT'
export const CHOOSING_START = 'CHOOSING_START'
export const CHOOSING_DEST = 'CHOOSING_DEST'
export const NOT_CHOOSING_START = 'NOT_CHOOSING_START'
export const NOT_CHOOSING_DEST = 'NOT_CHOOSING_DEST'
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD'

// SearchResult
export const SHOW_SEARCHRESULT = 'SHOW_SEARCHRESULT'
export const CLOSE_SEARCHRESULT = 'CLOSE_SEARCHRESULT'
export const SET_SEARCHRESULT = 'SET_SEARCHRESULT'

// SearchNav
export const SHOW_SEARCHNAV = 'SHOW_SEARCHNAV'
export const CLOSE_SEARCHNAV = 'CLOSE_SEARCHNAV'

// Hot
export const SHOW_HOT = 'SHOW_HOT'
export const CLOSE_HOT = 'CLOSE_HOT'
export const SET_HOTS = 'SET_HOTS'

// List
export const SHOW_LIST = 'SHOW_LIST'
export const CLOSE_LIST = 'CLOSE_LIST'
export const SHOW_BLOCKS = 'SHOW_BLOCKS'
export const SHOW_BUSINESSES = 'SHOW_BUSINESSES'
export const SHOW_TEAMS = 'SHOW_TEAMS'
export const SET_BLOCKS = 'SET_BLOCKS'
export const SET_BUSINESSES = 'SET_BUSINESSES'
export const SET_TEAMS = 'SET_TEAMS'
export const SET_DISPLAY = 'SET_DISPLAY'
export const SHOW_NOT_ALL_BLOCKS = 'SHOW_NOT_ALL_BLOCKS'
export const SHOW_NOT_ALL_BUSINESSES = 'SHOW_NOT_ALL_BUSINESSES'
export const SHOW_NOT_ALL_TEAMS = 'SHOW_NOT_ALL_TEAMS'

// Prompt
export const SHOW_PROMPT = 'SHOW_PROMPT'
export const CLOSE_PROMPT = 'CLOSE_PROMPT'
export const SET_PROMPT_DISPLAY = 'SET_PROMPT_DISPLAY'
export const CLEAR_PROMPT = 'CLEAR_PROMPT'

// Detail
export const SHOW_DETAIL = 'SHOW_DETAIL'
export const CLOSE_DETAIL = 'CLOSE_DETAIL'
export const SET_DISPLAY_DETAIL = 'SET_DISPLAY_DETAIL'
export const SHOW_BASE = 'SHOW_BASE'
export const SHOW_BUSINESS = 'SHOW_BUSINESS'